# Generated by Django 3.1.7 on 2021-04-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('career_id', models.IntegerField(primary_key=True, serialize=False)),
                ('career_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInform',
            fields=[
                ('line_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.IntegerField()),
                ('age', models.IntegerField()),
                ('career_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.career')),
            ],
        ),
    ]
