# Generated by Django 3.2.3 on 2021-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
