# Generated by Django 3.1.7 on 2021-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0002_auto_20210517_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='instantphotoanalysis',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
