# Generated by Django 3.2.3 on 2021-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0002_alter_diary_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='mood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
