# Generated by Django 3.1.7 on 2021-05-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0002_career_userinform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNote',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('default_note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultThing',
            fields=[
                ('things_id', models.IntegerField(primary_key=True, serialize=False)),
                ('things', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('mood', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='userinform',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')]),
        ),
        migrations.CreateModel(
            name='UserThings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.diary')),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.userinform')),
                ('things_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.defaultthing')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='line_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.userinform'),
        ),
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('line_id', 'date')},
        ),
    ]
