# Generated by Django 3.1.7 on 2021-05-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0003_auto_20210502_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinform',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
