# Generated by Django 3.1.7 on 2021-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0004_auto_20210507_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinform',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
