# Generated by Django 3.1.7 on 2021-05-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AI_analyze', '0005_auto_20210507_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisDiary',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='InstantPhotoAnalysis',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoAnalysis',
        ),
        migrations.RemoveField(
            model_name='userinform',
            name='age',
        ),
        migrations.AddField(
            model_name='userinform',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='career_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defaultnote',
            name='note_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defaultthing',
            name='things_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinform',
            name='career_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.career'),
        ),
        migrations.AlterField(
            model_name='userinform',
            name='gender',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='instantphotoanalysis',
            name='line_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.userinform'),
        ),
        migrations.AddField(
            model_name='analysisdiary',
            name='line_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AI_analyze.userinform'),
        ),
    ]
